apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: pihole
  namespace: pihole
  annotations:
    cert-manager.io/cluster-issuer: cloudflare 
spec:
  tls:
  - hosts:
    - pihole.k3s.techbabette.com
    secretName: pihole-cert 
  rules:
  - host: pihole.k3s.techbabette.com
    http:
      paths:
      - backend:
          service:
            name: pihole1
            port:
              number: 80
        path: /
        pathType: Prefix 
status:
  loadBalancer: {}
