apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  annotations:
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: cloudflare 
  name: longhorn
  namespace: longhorn-system
spec:
  tls:
    - hosts:
      - longhorn.k3s.techbabette.com
      secretName: longhorn-cert
  rules:
  - host: longhorn.k3s.techbabette.com
    http:
      paths:
      - backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
        path: /
        pathType: Prefix 
status:
  loadBalancer: {}
