apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: speedtest
  name: speedtest
  namespace: speedtest
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  - name: "443"
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: speedtest
  type: ClusterIP 
status:
  loadBalancer: {}
