apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dnsmasq
  namespace: pihole 
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-unsafe
  resources:
    requests:
      storage: 1Gi
